name: app-template
services:
    back:
        build: ./back-django
        # if you have a corresponding image hosted on Docker Hub, you can use an image definition instead of a build definition
        # image: YOUR-DOCKER-ID/IMAGE-NAME
        ports: 
            - 8000:8000
        # networks:
        #     - backend

    front:
        build: ./front-vue
        # if you have a corresponding image hosted on Docker Hub, you can use an image definition instead of a build definition
        # image: YOUR-DOCKER-ID/IMAGE-NAME
        ports: 
            - 5173:80
        depends_on:
            - back
        # networks:
        #     - backend
# networks:
#   backend:
#     driver: bridge
